### PR TITLE
Expand CODEOWNERS to include Robert, Kistine

### PR DESCRIPTION
**Pull request by lydiascarf**
This should make it easier to keep up with PRs

### CODE REVIEW

**Comment by BryanQuigley** [comment]
I'm open to this too, but I was thinking in the other thread of just adding them for [_datasets*](https://github.com/opendataphilly/opendataphilly-jkan/tree/main/_datasets)

**Comment by BryanQuigley** [comment]
Anyone with a GitHub account can make PRs :)

**Comment by lydiascarf** [comment]
@BryanQuigley thanks for the catch! that makes sense

**Review by BryanQuigley — APPROVED** [review]

**Comment by BryanQuigley** [comment]
thanks!

**Pull request merged**
